package cn.mlus.bettervannilafishes.init;

import cn.mlus.bettervannilafishes.BetterVannilaFishes;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.registries.DeferredRegister;

public class BvfCreativeTab {
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, BetterVannilaFishes.MODID);
    public static DeferredHolder<CreativeModeTab,CreativeModeTab> BVF_TAB = TABS.register("main", () -> CreativeModeTab.builder()
            .title(Component.translatable("itemGroup.bvf_group"))
            .icon(() -> BvfItems.MALE_SALMON_SPECIMEN.get().getDefaultInstance())
            .displayItems((par, output) -> {
               output.accept(BvfItems.HADDOCK_COD_SPAWN_EGG.get());
               output.accept(BvfItems.ATLANTIC_COD_SPAWN_EGG.get());
               output.accept(BvfItems.PACIFIC_COD_SPAWN_EGG.get());
               output.accept(BvfItems.MALE_SALMON_SPAWN_EGG.get());
               output.accept(BvfItems.FEMALE_SALMON_SPAWN_EGG.get());
               output.accept(BvfItems.PACIFIC_SALMON_SPAWN_EGG.get());
               output.accept(BvfItems.YELLOW_FIN_PUFFER_SPAWN_EGG.get());
               output.accept(BvfItems.OBSCURE_PUFFER_SPAWN_EGG.get());
               output.accept(BvfItems.PORCUPINE_FISH_SPAWN_EGG.get());
               output.accept(BvfItems.NAUTILUS_SPAWN_EGG.get());
               output.accept(BvfItems.FEATHER_STAR_SPAWN_EGG.get());
               output.accept(BvfItems.SPEARFISH_SPAWN_EGG.get());
               output.accept(BvfItems.ROOSTERFISH_SPAWN_EGG.get());
               output.accept(BvfItems.GALEOCERDO_CUVIER_SPAWN_EGG.get());
               output.accept(BvfItems.ALOPIAS_VULPINUS_SPAWN_EGG.get());
               output.accept(BvfItems.EPINEPHELUS_LANCEOLATUS_SPAWN_EGG.get());
               output.accept(BvfItems.EPINEPHELUS_ITAJARA_SPAWN_EGG.get());
               output.accept(BvfItems.EPINEPHELUS_MELANOSTIGMA_SPAWN_EGG.get());
               output.accept(BvfItems.ACANTHURUS_ACHILLES_SPAWN_EGG.get());
               output.accept(BvfItems.ACANTHURUS_LEUCOSTERNON_SPAWN_EGG.get());
               output.accept(BvfItems.PARACANTHURUS_HEPATUS_SPAWN_EGG.get());
               output.accept(BvfItems.ACANTHURUS_TRIOSTEGUS_SPAWN_EGG.get());
               output.accept(BvfItems.ACANTHURUS_NIGRICANS_SPAWN_EGG.get());
               output.accept(BvfItems.ACANTHURUS_LINEATUS_SPAWN_EGG.get());
               output.accept(BvfItems.AUSTRALOHEROS_FACETUS_SPAWN_EGG.get());
               output.accept(BvfItems.CICHLASOMA_BIMACULATUM_SPAWN_EGG.get());
               output.accept(BvfItems.KROBIA_GUIANENSIS_SPAWN_EGG.get());
               output.accept(BvfItems.AEQUIDENS_TETRAMERUS_SPAWN_EGG.get());
               output.accept(BvfItems.GYMNOGEOPHAGUS_BALZANII_SPAWN_EGG.get());
               output.accept(BvfItems.ASTRONOTUS_OCELLATUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_OCELLARIS_SPAWN_EGG.get());
               output.accept(BvfItems.PREMNAS_BIACULEATUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_POLYMNUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_PERIDERAION_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_CLARKII_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_PERCULA_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_AKINDYNOS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_BICINCTUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOGASTER_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOPTERUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_LATEZONATUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_MCCULLOCHI_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_MELANOPUS_SPAWN_EGG.get());
               output.accept(BvfItems.AMPHIPRION_TRICINCTUS_SPAWN_EGG.get());
               output.accept(BvfItems.DOSIDICUS_GIGAS_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_STRIATUS_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_UNIMACULATUS_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_AURIGA_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_COLLARE_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_RETICULATUS_SPAWN_EGG.get());
               output.accept(BvfItems.CHAETODON_SPECULUM_SPAWN_EGG.get());
               output.accept(BvfItems.CHANNA_MICROPELTES_SPAWN_EGG.get());
               output.accept(BvfItems.CHANNA_ARGUS_SPAWN_EGG.get());
               output.accept(BvfItems.ELOPICHTHYS_BAMBUSA_SPAWN_EGG.get());
               output.accept(BvfItems.HUSO_DAURICUS_SPAWN_EGG.get());
               output.accept(BvfItems.NEGAPRION_ACUTIDENS_SPAWN_EGG.get());
               output.accept(BvfItems.NEGAPRION_BREVIROSTRIS_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_SPLENDENS_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_IMBELLIS_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_SMARAGDINA_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_PICTA_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_SIMPLEX_SPAWN_EGG.get());
               output.accept(BvfItems.BETTA_BROWNORUM_SPAWN_EGG.get());
               output.accept(BvfItems.MEGALOPS_ATLANTICUS_SPAWN_EGG.get());
               output.accept(BvfItems.KATSUWONUS_PELAMIS_SPAWN_EGG.get());
               output.accept(BvfItems.BLACK_CARP_SPAWN_EGG.get());
               output.accept(BvfItems.GRASS_CARP_SPAWN_EGG.get());
               output.accept(BvfItems.SILVER_CARP_SPAWN_EGG.get());
               output.accept(BvfItems.BIGHEAD_CARP_SPAWN_EGG.get());
               output.accept(BvfItems.ZHIKONG_SCALLOP_SPAWN_EGG.get());
               output.accept(BvfItems.BAY_SCALLOP_SPAWN_EGG.get());
               output.accept(BvfItems.YESSO_SCALLOP_SPAWN_EGG.get());
                //Bucket
               output.accept(BvfItems.HADDOCK_COD_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ATLANTIC_COD_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.PACIFIC_COD_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.MALE_SALMON_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.FEMALE_SALMON_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.PACIFIC_SALMON_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.YELLOW_FIN_PUFFER_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.OBSCURE_PUFFER_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.PORCUPINE_FISH_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.NAUTILUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.FEATHER_STAR_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.SPEARFISH_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ROOSTERFISH_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.GALEOCERDO_CUVIER_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ALOPIAS_VULPINUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.EPINEPHELUS_LANCEOLATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.EPINEPHELUS_ITAJARA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.EPINEPHELUS_MELANOSTIGMA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ACANTHURUS_ACHILLES_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ACANTHURUS_LEUCOSTERNON_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.PARACANTHURUS_HEPATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ACANTHURUS_TRIOSTEGUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ACANTHURUS_NIGRICANS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ACANTHURUS_LINEATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AUSTRALOHEROS_FACETUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CICHLASOMA_BIMACULATUM_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.KROBIA_GUIANENSIS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AEQUIDENS_TETRAMERUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.GYMNOGEOPHAGUS_BALZANII_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ASTRONOTUS_OCELLATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_OCELLARIS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.PREMNAS_BIACULEATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_POLYMNUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_PERIDERAION_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_CLARKII_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_PERCULA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_AKINDYNOS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_BICINCTUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_CHRYSOGASTER_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_CHRYSOPTERUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_LATEZONATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_MCCULLOCHI_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_MELANOPUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.AMPHIPRION_TRICINCTUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.DOSIDICUS_GIGAS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_STRIATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_UNIMACULATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_AURIGA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_COLLARE_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_RETICULATUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHAETODON_SPECULUM_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHANNA_MICROPELTES_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.CHANNA_ARGUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ELOPICHTHYS_BAMBUSA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.HUSO_DAURICUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.NEGAPRION_ACUTIDENS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.NEGAPRION_BREVIROSTRIS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_SPLENDENS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_IMBELLIS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_SMARAGDINA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_PICTA_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_SIMPLEX_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BETTA_BROWNORUM_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.MEGALOPS_ATLANTICUS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.KATSUWONUS_PELAMIS_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BLACK_CARP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.GRASS_CARP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.SILVER_CARP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BIGHEAD_CARP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.ZHIKONG_SCALLOP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.BAY_SCALLOP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
               output.accept(BvfItems.YESSO_SCALLOP_BUCKET.get().getDefaultInstance(), CreativeModeTab.TabVisibility.PARENT_AND_SEARCH_TABS);
                //Food
               output.accept(BvfItems.HADDOCK_COD.get());
               output.accept(BvfItems.ATLANTIC_COD.get());
               output.accept(BvfItems.PACIFIC_COD.get());
               output.accept(BvfItems.MALE_SALMON.get());
               output.accept(BvfItems.FEMALE_SALMON.get());
               output.accept(BvfItems.PACIFIC_SALMON.get());
               output.accept(BvfItems.YELLOW_FIN_PUFFER.get());
               output.accept(BvfItems.OBSCURE_PUFFER.get());
               output.accept(BvfItems.PORCUPINE_FISH.get());
               output.accept(BvfItems.SPEARFISH.get());
               output.accept(BvfItems.COOKED_SPEARFISH.get());
               output.accept(BvfItems.ROOSTERFISH.get());
               output.accept(BvfItems.COOKED_ROOSTERFISH.get());
               output.accept(BvfItems.GALEOCERDO_CUVIER.get());
               output.accept(BvfItems.ALOPIAS_VULPINUS.get());
               output.accept(BvfItems.COOKED_ALOPIAS_VULPINUS.get());
               output.accept(BvfItems.NEGAPRION_ACUTIDENS.get());
               output.accept(BvfItems.COOKED_NEGAPRION_ACUTIDENS.get());
               output.accept(BvfItems.NEGAPRION_BREVIROSTRIS.get());
               output.accept(BvfItems.COOKED_NEGAPRION_BREVIROSTRIS.get());
               output.accept(BvfItems.EPINEPHELUS_LANCEOLATUS.get());
               output.accept(BvfItems.EPINEPHELUS_ITAJARA.get());
               output.accept(BvfItems.EPINEPHELUS_MELANOSTIGMA.get());
               output.accept(BvfItems.COOKED_EPINEPHELUS.get());
               output.accept(BvfItems.SHARK_FIN.get());
               output.accept(BvfItems.ACANTHURUS_ACHILLES.get());
               output.accept(BvfItems.ACANTHURUS_LEUCOSTERNON.get());
               output.accept(BvfItems.PARACANTHURUS_HEPATUS.get());
               output.accept(BvfItems.ACANTHURUS_TRIOSTEGUS.get());
               output.accept(BvfItems.ACANTHURUS_NIGRICANS.get());
               output.accept(BvfItems.ACANTHURUS_LINEATUS.get());
               output.accept(BvfItems.AUSTRALOHEROS_FACETUS.get());
               output.accept(BvfItems.CICHLASOMA_BIMACULATUM.get());
               output.accept(BvfItems.KROBIA_GUIANENSIS.get());
               output.accept(BvfItems.AEQUIDENS_TETRAMERUS.get());
               output.accept(BvfItems.GYMNOGEOPHAGUS_BALZANII.get());
               output.accept(BvfItems.ASTRONOTUS_OCELLATUS.get());
               output.accept(BvfItems.AMPHIPRION_OCELLARIS.get());
               output.accept(BvfItems.PREMNAS_BIACULEATUS.get());
               output.accept(BvfItems.AMPHIPRION_POLYMNUS.get());
               output.accept(BvfItems.AMPHIPRION_PERIDERAION.get());
               output.accept(BvfItems.AMPHIPRION_CLARKII.get());
               output.accept(BvfItems.AMPHIPRION_PERCULA.get());
               output.accept(BvfItems.AMPHIPRION_AKINDYNOS.get());
               output.accept(BvfItems.AMPHIPRION_BICINCTUS.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOGASTER.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOPTERUS.get());
               output.accept(BvfItems.AMPHIPRION_LATEZONATUS.get());
               output.accept(BvfItems.AMPHIPRION_MCCULLOCHI.get());
               output.accept(BvfItems.AMPHIPRION_MELANOPUS.get());
               output.accept(BvfItems.AMPHIPRION_TRICINCTUS.get());
               output.accept(BvfItems.HUMBOLDT_SQUID.get());
               output.accept(BvfItems.COOKED_HUMBOLDT_SQUID.get());
               output.accept(BvfItems.FEATHER_STAR_TENTACLE.get());
               output.accept(BvfItems.CHAETODON_STRIATUS.get());
               output.accept(BvfItems.CHAETODON_UNIMACULATUS.get());
               output.accept(BvfItems.CHAETODON_AURIGA.get());
               output.accept(BvfItems.CHAETODON_COLLARE.get());
               output.accept(BvfItems.CHAETODON_RETICULATUS.get());
               output.accept(BvfItems.CHAETODON_SPECULUM.get());
               output.accept(BvfItems.CHANNA_MICROPELTES.get());
               output.accept(BvfItems.CHANNA_ARGUS.get());
               output.accept(BvfItems.COOKED_CHANNA.get());
               output.accept(BvfItems.ELOPICHTHYS_BAMBUSA.get());
               output.accept(BvfItems.COOKED_ELOPICHTHYS_BAMBUSA.get());
               output.accept(BvfItems.HUSO_DAURICUS.get());
               output.accept(BvfItems.COOKED_HUSO_DAURICUS.get());
               output.accept(BvfItems.BETTA_SPLENDENS.get());
               output.accept(BvfItems.BETTA_IMBELLIS.get());
               output.accept(BvfItems.BETTA_SMARAGDINA.get());
               output.accept(BvfItems.BETTA_PICTA.get());
               output.accept(BvfItems.BETTA_SIMPLEX.get());
               output.accept(BvfItems.BETTA_BROWNORUM.get());
               output.accept(BvfItems.MEGALOPS_ATLANTICUS.get());
               output.accept(BvfItems.KATSUWONUS_PELAMIS.get());
               output.accept(BvfItems.COOKED_KATSUWONUS_PELAMIS.get());
               output.accept(BvfItems.BLACK_CARP.get());
               output.accept(BvfItems.COOKED_BLACK_CARP.get());
               output.accept(BvfItems.GRASS_CARP.get());
               output.accept(BvfItems.COOKED_GRASS_CARP.get());
               output.accept(BvfItems.SILVER_CARP.get());
               output.accept(BvfItems.COOKED_SILVER_CARP.get());
               output.accept(BvfItems.BIGHEAD_CARP.get());
               output.accept(BvfItems.COOKED_BIGHEAD_CARP.get());
               output.accept(BvfItems.SCALLOP_MEAT.get());
                //Specimen
               output.accept(BvfItems.HADDOCK_COD_SPECIMEN.get());
               output.accept(BvfItems.ATLANTIC_COD_SPECIMEN.get());
               output.accept(BvfItems.PACIFIC_COD_SPECIMEN.get());
               output.accept(BvfItems.PACIFIC_SALMON_SPECIMEN.get());
               output.accept(BvfItems.MALE_SALMON_SPECIMEN.get());
               output.accept(BvfItems.FEMALE_SALMON_SPECIMEN.get());
               output.accept(BvfItems.SPEARFISH_SPECIMEN.get());
               output.accept(BvfItems.ROOSTERFISH_SPECIMEN.get());
               output.accept(BvfItems.GALEOCERDO_CUVIER_SPECIMEN.get());
               output.accept(BvfItems.ALOPIAS_VULPINUS_SPECIMEN.get());
               output.accept(BvfItems.EPINEPHELUS_LANCEOLATUS_SPECIMEN.get());
               output.accept(BvfItems.EPINEPHELUS_ITAJARA_SPECIMEN.get());
               output.accept(BvfItems.EPINEPHELUS_MELANOSTIGMA_SPECIMEN.get());
               output.accept(BvfItems.AUSTRALOHEROS_FACETUS_SPECIMEN.get());
               output.accept(BvfItems.CICHLASOMA_BIMACULATUM_SPECIMEN.get());
               output.accept(BvfItems.KROBIA_GUIANENSIS_SPECIMEN.get());
               output.accept(BvfItems.AEQUIDENS_TETRAMERUS_SPECIMEN.get());
               output.accept(BvfItems.GYMNOGEOPHAGUS_BALZANII_SPECIMEN.get());
               output.accept(BvfItems.ASTRONOTUS_OCELLATUS_SPECIMEN.get());
               output.accept(BvfItems.CHANNA_MICROPELTES_SPECIMEN.get());
               output.accept(BvfItems.CHANNA_ARGUS_SPECIMEN.get());
               output.accept(BvfItems.ELOPICHTHYS_BAMBUSA_SPECIMEN.get());
               output.accept(BvfItems.HUSO_DAURICUS_SPECIMEN.get());
               output.accept(BvfItems.MEGALOPS_ATLANTICUS_SPECIMEN.get());
               output.accept(BvfItems.KATSUWONUS_PELAMIS_SPECIMEN.get());
               output.accept(BvfItems.NEGAPRION_ACUTIDENS_SPECIMEN.get());
               output.accept(BvfItems.NEGAPRION_BREVIROSTRIS_SPECIMEN.get());
               output.accept(BvfItems.BLACK_CARP_SPECIMEN.get());
               output.accept(BvfItems.GRASS_CARP_SPECIMEN.get());
               output.accept(BvfItems.SILVER_CARP_SPECIMEN.get());
               output.accept(BvfItems.BIGHEAD_CARP_SPECIMEN.get());
               output.accept(BvfItems.OBSCURE_PUFFER_SPECIMEN.get());
               output.accept(BvfItems.YELLOW_FIN_PUFFER_SPECIMEN.get());
               output.accept(BvfItems.PORCUPINE_FISH_SPECIMEN.get());
               output.accept(BvfItems.BETTA_SPLENDENS_SPECIMEN.get());
               output.accept(BvfItems.BETTA_IMBELLIS_SPECIMEN.get());
               output.accept(BvfItems.BETTA_SMARAGDINA_SPECIMEN.get());
               output.accept(BvfItems.BETTA_PICTA_SPECIMEN.get());
               output.accept(BvfItems.BETTA_SIMPLEX_SPECIMEN.get());
               output.accept(BvfItems.BETTA_BROWNORUM_SPECIMEN.get());
               output.accept(BvfItems.ACANTHURUS_ACHILLES_SPECIMEN.get());
               output.accept(BvfItems.ACANTHURUS_LEUCOSTERNON_SPECIMEN.get());
               output.accept(BvfItems.PARACANTHURUS_HEPATUS_SPECIMEN.get());
               output.accept(BvfItems.ACANTHURUS_TRIOSTEGUS_SPECIMEN.get());
               output.accept(BvfItems.ACANTHURUS_NIGRICANS_SPECIMEN.get());
               output.accept(BvfItems.ACANTHURUS_LINEATUS_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_STRIATUS_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_UNIMACULATUS_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_AURIGA_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_COLLARE_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_RETICULATUS_SPECIMEN.get());
               output.accept(BvfItems.CHAETODON_SPECULUM_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_OCELLARIS_SPECIMEN.get());
               output.accept(BvfItems.PREMNAS_BIACULEATUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_POLYMNUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_PERIDERAION_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_CLARKII_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_PERCULA_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_AKINDYNOS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_BICINCTUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOGASTER_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_CHRYSOPTERUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_LATEZONATUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_MCCULLOCHI_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_MELANOPUS_SPECIMEN.get());
               output.accept(BvfItems.AMPHIPRION_TRICINCTUS_SPECIMEN.get());
            }).build());

    public static void register(IEventBus eventBus) {
        TABS.register(eventBus);
    }
}
